import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import mongoose from 'mongoose';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import Donor from './models/Donor.js';
import BloodRequest from './models/BloodRequest.js';
import User from './models/User.js';
dotenv.config();
const app=express(), PORT=process.env.PORT||5000; let mongo=false;
const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
const dataDir=path.join(__dirname,'data');
const usersFile=path.join(dataDir,'users.json');
if(!fs.existsSync(dataDir)) fs.mkdirSync(dataDir,{recursive:true});
app.use(cors({origin:true})); app.use(express.json({limit:'1mb'}));
const groups=['A+','A-','B+','B-','AB+','AB-','O+','O-'];
const compatible={"A+":["A+","A-","O+","O-"],"A-":["A-","O-"],"B+":["B+","B-","O+","O-"],"B-":["B-","O-"],"AB+":groups,"AB-":["AB-","A-","B-","O-"],"O+":["O+","O-"],"O-":["O-"]};
const demoDonors=[
 {_id:'d1',name:'Arun Kumar',age:24,bloodGroup:'O+',city:'Chennai',area:'Velachery',pin:'600042',phone:'9876543210',email:'arun@example.com',available:true,lastDonation:'2026-06-15',verified:true,lat:12.9815,lng:80.2180,history:['2026-06-15','2025-12-10']},
 {_id:'d2',name:'Priya S',age:27,bloodGroup:'A+',city:'Chennai',area:'Adyar',pin:'600020',phone:'9876501234',email:'priya@example.com',available:true,lastDonation:'2026-05-20',verified:true,lat:13.0012,lng:80.2565,history:['2026-05-20','2025-11-02']},
 {_id:'d3',name:'Karthik R',age:31,bloodGroup:'B+',city:'Tambaram',area:'West Tambaram',pin:'600045',phone:'9865432109',email:'karthik@example.com',available:true,lastDonation:'2026-07-01',verified:true,lat:12.9249,lng:80.1000,history:['2026-07-01']},
 {_id:'d4',name:'Divya M',age:23,bloodGroup:'O-',city:'Chengalpattu',area:'Town',pin:'603001',phone:'9854321098',email:'divya@example.com',available:false,lastDonation:'2026-04-10',verified:true,lat:12.6811,lng:79.9837,history:['2026-04-10','2025-08-20']},
 {_id:'d5',name:'Sanjay P',age:29,bloodGroup:'AB+',city:'Chennai',area:'Guindy',pin:'600032',phone:'9845012345',email:'sanjay@example.com',available:true,lastDonation:'2026-08-03',verified:false,lat:13.0067,lng:80.2206,history:['2026-08-03']},
 {_id:'d6',name:'Meena Devi',age:26,bloodGroup:'A-',city:'Chennai',area:'Anna Nagar',pin:'600040',phone:'9834567812',email:'meena@example.com',available:true,lastDonation:'2026-05-08',verified:true,lat:13.0850,lng:80.2101,history:['2026-05-08','2025-10-18']},
 {_id:'d7',name:'Vijay Anand',age:34,bloodGroup:'B-',city:'Chennai',area:'T Nagar',pin:'600017',phone:'9823456712',email:'vijay@example.com',available:true,lastDonation:'2026-07-22',verified:true,lat:13.0418,lng:80.2341,history:['2026-07-22','2026-01-12']},
 {_id:'d8',name:'Nithya K',age:25,bloodGroup:'O+',city:'Chennai',area:'Mylapore',pin:'600004',phone:'9812345678',email:'nithya@example.com',available:true,lastDonation:'2026-06-28',verified:true,lat:13.0335,lng:80.2694,history:['2026-06-28']},
 {_id:'d9',name:'Rahul S',age:30,bloodGroup:'AB-',city:'Tambaram',area:'East Tambaram',pin:'600059',phone:'9801234567',email:'rahul@example.com',available:false,lastDonation:'2026-08-12',verified:true,lat:12.9398,lng:80.1477,history:['2026-08-12']},
 {_id:'d10',name:'Aishwarya V',age:28,bloodGroup:'B+',city:'Chennai',area:'Porur',pin:'600116',phone:'9798765432',email:'aishwarya@example.com',available:true,lastDonation:'2026-06-05',verified:false,lat:13.0358,lng:80.1565,history:['2026-06-05','2025-12-01']},
 {_id:'dDemo',name:'Demo LifeLink User',age:25,bloodGroup:'O+',city:'Chennai',area:'Velachery',pin:'600042',phone:'9876543210',email:'demo@lifelink.test',available:true,lastDonation:'2026-06-15',verified:true,lat:12.9815,lng:80.2180,history:['2026-06-15']}
];
let donors=[...demoDonors], requests=[
 {_id:'r1',patientName:'Emergency Patient',patientId:'P-1001',bloodGroup:'O+',hospital:'City Hospital',city:'Chennai',units:2,contact:'9000011111',urgency:'Urgent',status:'Open',requiredAt:'2026-10-03T18:30',createdAt:new Date().toISOString(),lat:13.0475,lng:80.2095},
 {_id:'r2',patientName:'Ravi',patientId:'P-1002',bloodGroup:'A+',hospital:'Apollo Medical Centre',city:'Chennai',units:1,contact:'9000022222',urgency:'Normal',status:'Open',requiredAt:'2026-10-04T10:00',createdAt:new Date().toISOString(),lat:13.0569,lng:80.2425},
 {_id:'r3',patientName:'Lakshmi',patientId:'P-1003',bloodGroup:'B+',hospital:'Sri Ramachandra Hospital',city:'Porur',units:2,contact:'9000033333',urgency:'Urgent',status:'Donor Found',requiredAt:'2026-10-03T16:00',createdAt:new Date().toISOString(),lat:13.0382,lng:80.1431},
 {_id:'r4',patientName:'Mohan',patientId:'P-1004',bloodGroup:'AB+',hospital:'MIOT International',city:'Chennai',units:1,contact:'9000044444',urgency:'Normal',status:'Fulfilled',requiredAt:'2026-09-30T12:00',createdAt:new Date().toISOString(),lat:13.0215,lng:80.2070},
 {_id:'r5',patientName:'Kavya',patientId:'P-1005',bloodGroup:'O-',hospital:'Government General Hospital',city:'Chennai',units:3,contact:'9000055555',urgency:'Urgent',status:'Open',requiredAt:'2026-10-03T20:00',createdAt:new Date().toISOString(),lat:13.0780,lng:80.2820},
 {_id:'r6',patientName:'Suresh',patientId:'P-1006',bloodGroup:'A-',hospital:'Gleneagles HealthCity',city:'Perumbakkam',units:1,contact:'9000066666',urgency:'Normal',status:'Open',requiredAt:'2026-10-05T09:30',createdAt:new Date().toISOString(),lat:12.8970,lng:80.2209},
 {_id:'r7',patientName:'Anitha',patientId:'P-1007',bloodGroup:'B-',hospital:'Deepam Hospitals',city:'Tambaram',units:2,contact:'9000077777',urgency:'Urgent',status:'Donor Found',requiredAt:'2026-10-04T14:00',createdAt:new Date().toISOString(),lat:12.9240,lng:80.1270},
 {_id:'r8',patientName:'Manoj',patientId:'P-1008',bloodGroup:'AB-',hospital:'Kauvery Hospital',city:'Alwarpet',units:1,contact:'9000088888',urgency:'Normal',status:'Fulfilled',requiredAt:'2026-09-28T11:00',createdAt:new Date().toISOString(),lat:13.0330,lng:80.2550}
];
let inventory={ 'A+':{group:'A+',units:18},'A-':{group:'A-',units:3},'B+':{group:'B+',units:9},'B-':{group:'B-',units:2},'AB+':{group:'AB+',units:7},'AB-':{group:'AB-',units:1},'O+':{group:'O+',units:5},'O-':{group:'O-',units:1} };
let users=[];
try { users=JSON.parse(fs.readFileSync(usersFile,'utf8')); if(!Array.isArray(users)) users=[]; } catch { users=[]; }
const hash=p=>{const salt=crypto.randomBytes(16).toString('hex');return {salt,hash:crypto.scryptSync(String(p),salt,64).toString('hex')}};
const check=(p,h,s)=>crypto.timingSafeEqual(crypto.scryptSync(String(p),s,64),Buffer.from(h,'hex'));
const token=()=>crypto.randomBytes(32).toString('hex');
const saveUsers=()=>{try{fs.writeFileSync(usersFile,JSON.stringify(users,null,2));}catch{}};
// Keep one deterministic demo account available for project demonstrations.
const demoProfile={name:'Demo LifeLink User',age:25,bloodGroup:'O+',city:'Chennai',area:'Velachery',pin:'600042',phone:'9876543210',email:'demo@lifelink.test',lastDonation:'2026-06-15',available:true,lat:12.9815,lng:80.218};
let demoUser=users.find(u=>u.email==='demo@lifelink.test');
if(!demoUser){
  const demoHash=hash('LifeLink123');
  demoUser={id:'udemo001',name:'Demo LifeLink User',email:'demo@lifelink.test',role:'donor',passwordHash:demoHash.hash,salt:demoHash.salt,verified:true,createdAt:new Date().toISOString(),donorId:'dDemo',profile:demoProfile};
  users.push(demoUser);
  saveUsers();
}else {
  const demoHash=hash('LifeLink123');
  demoUser.name='Demo LifeLink User'; demoUser.role='donor'; demoUser.verified=true; demoUser.passwordHash=demoHash.hash; demoUser.salt=demoHash.salt; demoUser.donorId='dDemo'; demoUser.profile=demoProfile; saveUsers();
}

let sessions=new Map(), notifications=[];
function auth(req,res,next){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,''); if(!t||!sessions.has(t)) return res.status(401).json({message:'Authentication required'}); req.user=sessions.get(t); next();}
function hav(a,b,c,d){const R=6371,rad=x=>x*Math.PI/180;const x=rad(c-a),y=rad(d-b);const q=Math.sin(x/2)**2+Math.cos(rad(a))*Math.cos(rad(c))*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
app.get('/api/health',(req,res)=>res.json({ok:true,database:mongo?'MongoDB':'Demo mode',features:['smart-search','requests','inventory','analytics','auth','notifications']}));
app.post('/api/auth/register',async(req,res)=>{try{let {name,email,password,role='patient'}=req.body||{};name=String(name||'').trim();email=String(email||'').trim().toLowerCase();role=['patient','donor','hospital','requester','admin'].includes(role)?role:'patient';if(!name||!email||!password)return res.status(400).json({message:'Name, email and password are required.'});if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return res.status(400).json({message:'Please enter a valid email address.'});if(String(password).length<6)return res.status(400).json({message:'Password must contain at least 6 characters.'});if(users.some(u=>u.email===email))return res.status(409).json({message:'This email is already registered. Please sign in instead.'});const h=hash(password),u={id:'u'+Date.now()+crypto.randomBytes(3).toString('hex'),name,email,role,passwordHash:h.hash,salt:h.salt,verified:false,createdAt:new Date().toISOString(),donorId:null,profile:null};users.push(u);saveUsers();res.status(201).json({message:'Account created successfully. Please sign in with your email and password.',user:{id:u.id,name,email,role,verified:false}})}catch(e){console.error(e);res.status(500).json({message:'Registration failed. Please try again.'})}});
app.post('/api/auth/login',(req,res)=>{const email=String(req.body?.email||'').toLowerCase().trim(),u=users.find(x=>x.email===email);if(!u||!check(req.body.password,u.passwordHash,u.salt))return res.status(401).json({message:'Incorrect email or password.'});const t=token();sessions.set(t,u);res.json({message:'Login successful.',token:t,user:{id:u.id,name:u.name,email:u.email,role:u.role,verified:u.verified,donorId:u.donorId||null,profile:u.profile||null}})});
app.post('/api/auth/logout',auth,(req,res)=>{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');sessions.delete(t);res.json({ok:true})});
app.post('/api/auth/verify',auth,(req,res)=>{req.user.verified=true;saveUsers();res.json({ok:true,message:'Email verified in demo mode.'})});
app.post('/api/auth/forgot-password',(req,res)=>res.json({ok:true,message:'If the account exists, a reset link would be sent. Demo mode does not send email.'}));
app.get('/api/me',auth,(req,res)=>res.json({user:{id:req.user.id,name:req.user.name,email:req.user.email,role:req.user.role,verified:req.user.verified,donorId:req.user.donorId||null,profile:req.user.profile||null}}));
app.get('/api/profile',auth,(req,res)=>res.json({profile:req.user.profile||null,donorId:req.user.donorId||null}));
app.patch('/api/profile',auth,(req,res)=>{try{const b=req.body||{};const profile={name:String(b.name||req.user.name).trim(),age:Number(b.age)||'',bloodGroup:String(b.bloodGroup||'').trim(),city:String(b.city||'').trim(),area:String(b.area||'').trim(),pin:String(b.pin||'').trim(),phone:String(b.phone||'').trim(),email:String(b.email||req.user.email).trim().toLowerCase(),lastDonation:String(b.lastDonation||'').trim(),available:b.available!==false,lat:Number(b.lat)||13.0827,lng:Number(b.lng)||80.2707};if(!profile.name||!profile.bloodGroup||!profile.city||!profile.phone)return res.status(400).json({message:'Name, blood group, city and phone are required.'});if(!groups.includes(profile.bloodGroup))return res.status(400).json({message:'Please select a valid blood group.'});if(!/^\d{6}$/.test(profile.pin))return res.status(400).json({message:'PIN code must contain 6 digits.'});if(!/^\d{10}$/.test(profile.phone.replace(/\D/g,'')))return res.status(400).json({message:'Phone number must contain 10 digits.'});let d;if(req.user.donorId){const i=donors.findIndex(x=>x._id===req.user.donorId);if(i>=0){d={...donors[i],...profile};donors[i]=d}else req.user.donorId=null}if(!req.user.donorId){d={_id:'duser'+Date.now()+crypto.randomBytes(2).toString('hex'),...profile,verified:false,history:[]};donors.unshift(d);req.user.donorId=d._id}else{d=donors.find(x=>x._id===req.user.donorId)}req.user.profile=profile;req.user.name=profile.name;req.user.email=profile.email;saveUsers();res.json({message:'Donor profile saved successfully.',profile,donor:d,donorId:req.user.donorId})}catch(e){console.error(e);res.status(500).json({message:'Could not save donor profile.'})}});
app.delete('/api/profile',auth,(req,res)=>{if(!req.user.donorId)return res.status(404).json({message:'No saved donor profile found.'});const i=donors.findIndex(x=>x._id===req.user.donorId);if(i>=0)donors.splice(i,1);notifications=notifications.filter(n=>n.donorId!==req.user.donorId);req.user.donorId=null;req.user.profile=null;saveUsers();res.json({message:'Your donor profile was deleted successfully.'})});
app.get('/api/donors',async(req,res)=>{try{const {recipientGroup,bloodGroup,city,area,pin,lat,lng,radius=50,available='true'}=req.query;let list;if(mongo){list=await Donor.find({available:available!=='false'}).lean();if(!list.length)list=donors.filter(d=>available==='false'||d.available)}else{list=donors.filter(d=>available==='false'||d.available)}const allowed=recipientGroup?compatible[recipientGroup]:bloodGroup?[bloodGroup]:null;if(recipientGroup&&!allowed)return res.status(400).json({message:'Invalid recipient blood group.'});if(allowed)list=list.filter(d=>allowed.includes(d.bloodGroup));if(city)list=list.filter(d=>String(d.city||'').toLowerCase().includes(String(city).trim().toLowerCase()));if(area)list=list.filter(d=>String(d.area||'').toLowerCase().includes(String(area).trim().toLowerCase()));if(pin)list=list.filter(d=>String(d.pin||'').includes(String(pin).trim()));if(lat&&lng){const userLat=Number(lat),userLng=Number(lng),maxRadius=Number(radius)||50;list=list.map(d=>{const dLat=Number(d.lat),dLng=Number(d.lng);return Number.isFinite(dLat)&&Number.isFinite(dLng)?{...d,distanceKm:hav(userLat,userLng,dLat,dLng)}:{...d,distanceKm:null}}).filter(d=>d.distanceKm===null||d.distanceKm<=maxRadius).sort((a,b)=>(a.distanceKm??999999)-(b.distanceKm??999999))}else{list.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||'')))}res.json(list)}catch(e){console.error('Donor search error:',e);res.status(500).json({message:'Unable to search donors. Please restart the LifeLink backend.'})}});
app.get('/api/donors/:id',(req,res)=>{const d=donors.find(x=>x._id===req.params.id);d?res.json(d):res.status(404).json({message:'Donor not found'})});
app.post('/api/donors',async(req,res)=>{const d={_id:'d'+Date.now(),...req.body,age:+req.body.age,available:true,verified:false,history:[],lat:+req.body.lat||13.0827,lng:+req.body.lng||80.2707};if(!d.name||!d.bloodGroup||!d.city||!d.phone)return res.status(400).json({message:'Complete required donor fields.'});donors.unshift(d);res.status(201).json(d)});
app.patch('/api/donors/:id/availability',auth,(req,res)=>{const d=donors.find(x=>x._id===req.params.id);if(!d)return res.status(404).json({message:'Donor not found'});d.available=!!req.body.available;res.json(d)});
app.patch('/api/donors/:id',auth,(req,res)=>{const i=donors.findIndex(x=>x._id===req.params.id);if(i<0)return res.status(404).json({message:'Donor not found'});const current=donors[i];const allowed=['name','age','bloodGroup','city','area','pin','phone','email','lastDonation','lat','lng','available'];const next={...current};for(const key of allowed){if(req.body[key]!==undefined)next[key]=key==='age'||key==='lat'||key==='lng'?Number(req.body[key]):key==='available'?Boolean(req.body[key]):String(req.body[key]??'').trim()}if(!next.name||!next.bloodGroup||!next.city||!next.phone)return res.status(400).json({message:'Name, blood group, city and phone are required.'});if(!groups.includes(next.bloodGroup))return res.status(400).json({message:'Invalid blood group.'});donors[i]=next;res.json({message:'Donor profile updated successfully.',donor:next})});
app.delete('/api/donors/:id',auth,(req,res)=>{const i=donors.findIndex(x=>x._id===req.params.id);if(i<0)return res.status(404).json({message:'Donor not found'});const removed=donors.splice(i,1)[0];notifications=notifications.filter(n=>n.donorId!==removed._id);res.json({message:'Donor profile deleted successfully.',id:removed._id})});
app.get('/api/requests',(req,res)=>res.json(requests));
app.post('/api/requests',(req,res)=>{const r={_id:'r'+Date.now(),...req.body,units:+req.body.units,status:'Open',createdAt:new Date().toISOString()};if(!r.patientName||!r.bloodGroup||!r.hospital||!r.city)return res.status(400).json({message:'Complete request details.'});requests.unshift(r);const matches=donors.filter(d=>d.available&&compatible[r.bloodGroup]?.includes(d.bloodGroup));matches.forEach(d=>notifications.unshift({id:Date.now()+Math.random(),donorId:d._id,title:`${r.urgency} ${r.bloodGroup} Blood Needed`,body:`${r.hospital} • ${r.city}`,requestId:r._id,read:false,createdAt:new Date().toISOString()}));res.status(201).json({...r,matchedDonors:matches.length})});
app.patch('/api/requests/:id/status',auth,(req,res)=>{const r=requests.find(x=>x._id===req.params.id);if(!r)return res.status(404).json({message:'Request not found'});r.status=req.body.status;res.json(r)});
app.patch('/api/requests/:id',auth,(req,res)=>{const i=requests.findIndex(x=>x._id===req.params.id);if(i<0)return res.status(404).json({message:'Request not found'});const current=requests[i];const allowed=['patientName','patientId','bloodGroup','units','hospital','city','contact','requiredAt','urgency','status','lat','lng'];const next={...current};for(const key of allowed){if(req.body[key]!==undefined)next[key]=['units','lat','lng'].includes(key)?Number(req.body[key]):String(req.body[key]??'').trim()}if(!next.patientName||!next.bloodGroup||!next.hospital||!next.city)return res.status(400).json({message:'Patient name, blood group, hospital and city are required.'});if(!groups.includes(next.bloodGroup))return res.status(400).json({message:'Invalid blood group.'});if(!['Normal','Urgent','Critical'].includes(next.urgency))return res.status(400).json({message:'Invalid priority.'});if(!['Open','Donor Found','Fulfilled'].includes(next.status))return res.status(400).json({message:'Invalid request status.'});requests[i]=next;res.json({message:'Blood request updated successfully.',request:next})});
app.delete('/api/requests/:id',auth,(req,res)=>{const i=requests.findIndex(x=>x._id===req.params.id);if(i<0)return res.status(404).json({message:'Request not found'});const removed=requests.splice(i,1)[0];notifications=notifications.filter(n=>n.requestId!==removed._id);res.json({message:'Blood request deleted successfully.',id:removed._id})});
app.get('/api/requests/:id/matches',(req,res)=>{const r=requests.find(x=>x._id===req.params.id);if(!r)return res.status(404).json({message:'Request not found'});const list=donors.filter(d=>d.available&&compatible[r.bloodGroup]?.includes(d.bloodGroup)).map(d=>({...d,distanceKm:r.lat?hav(r.lat,r.lng,d.lat,d.lng):null})).sort((a,b)=>(a.distanceKm??999)-(b.distanceKm??999));res.json(list)});
app.get('/api/notifications',auth,(req,res)=>res.json(notifications.filter(n=>n.donorId===req.user.donorId||!req.user.donorId).slice(0,30)));
app.patch('/api/notifications/:id/read',auth,(req,res)=>{const n=notifications.find(x=>String(x.id)===req.params.id);if(n)n.read=true;res.json({ok:true})});
app.get('/api/inventory',(req,res)=>res.json(Object.values(inventory).map(x=>({...x,status:x.units<=2?'Critical':x.units<=4?'Low':'Available'}))));
app.patch('/api/inventory/:group',auth,(req,res)=>{if(!inventory[req.params.group])return res.status(404).json({message:'Group not found'});inventory[req.params.group].units=Math.max(0,+req.body.units||0);res.json(inventory[req.params.group])});
app.get('/api/analytics',(req,res)=>{const byGroup=Object.fromEntries(groups.map(g=>[g,requests.filter(r=>r.bloodGroup===g).length]));res.json({donors:donors.length,activeDonors:donors.filter(d=>d.available).length,requests:requests.length,pending:requests.filter(r=>r.status!=='Fulfilled').length,fulfilled:requests.filter(r=>r.status==='Fulfilled').length,hospitals:new Set(requests.map(r=>r.hospital)).size,byGroup,cities:Object.fromEntries([...new Set(requests.map(r=>r.city))].map(c=>[c,requests.filter(r=>r.city===c).length]))})});
app.get('/api/activity',(req,res)=>res.json([{time:new Date().toISOString(),event:'System health checked',actor:'system'},{time:new Date().toISOString(),event:`${requests.length} live requests tracked`,actor:'system'},{time:new Date().toISOString(),event:`${donors.filter(d=>d.available).length} active donors`,actor:'system'}]));
app.use(express.static(path.join(__dirname,'..','client','dist')));app.get('*',(req,res)=>req.path.startsWith('/api/')?res.status(404).json({message:'API route not found'}):res.sendFile(path.join(__dirname,'..','client','dist','index.html')));
if(process.env.MONGO_URI){try{await mongoose.connect(process.env.MONGO_URI,{serverSelectionTimeoutMS:3000});mongo=true}catch{}}app.listen(PORT,'0.0.0.0',()=>console.log(`LifeLink API on ${PORT} (${mongo?'MongoDB':'Demo mode'})`));
